name: helloworld
description: A sample "Hello, World!" Functions Framework project.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  functions_framework:
  shelf:
  shelf_router:
  firedart:
  uuid:
  intl:
  timeago:


dev_dependencies:
  build_runner:
  functions_framework_builder:
  http:
  lints:
  test:
  test_process:

handlers:
  - url: /.*
    http_headers:
      Access-Control-Allow-Origin: '*'